### ISSUE TITLE
Graphical display instead of ASCII

### ISSUE THREAD

**Issue by dannnav** [faab64/OLED_on_ZedBoard#1]
Hi,
How can I write graphical display (such as fft spectrum) instead of characters?

Thanks,
Danna

**Comment by faab64** [comment]
Hi Danna,
The code is a bit complicated because of generation of the character mapping, if you want to use it as a simple graphic display, you can read the datasheet and I am sure you can figure it out pretty easily. 

I may have the code somewhere, I will put it here if I find it!

Best regards,
Farhad

**Comment by faab64** [comment]
As this is out of the scope of this little project, I am closing this.
